language: "en-US" # USA English

# CodeRabbit is used in MANUAL, COMMENT-TRIGGERED mode.
# There are NO automatic PR reviews.
# Reviews apply ONLY to new commits (incremental by design).
# A collapsed walkthrough may be produced when explicitly triggered.

reviews:
  profile: "assertive" # More feedback, may be nitpicky (intentional for SDKs)

  # Disable spammy / conversational behavior
  high_level_summary: false
  review_status: false
  commit_status: false
  in_progress_fortune: false
  poem: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  enable_prompt_for_ai_agents: false

  # Walkthrough behavior
  collapse_walkthrough: true

  # IMPORTANT: manual review only
  auto: false
  auto_comment: false

  path_instructions:
    # =====================================================
    # EXAMPLES
    # =====================================================
    - path: "examples/**/*"
      instructions: |
        You are acting as a senior maintainer reviewing SDK examples.
        Examples must work verbatim for users who copy-paste them.

        PRIORITY 1 — Correctness:
        - Verify transaction lifecycle: construct → freeze_with → sign → execute.
        - `freeze_with(client)` MUST be called before signing.
        - Ensure all referenced methods exist in `hiero_sdk_python`.
        - Validate receipts against `ResponseCode` enums (e.g., `ResponseCode.SUCCESS`).

        PRIORITY 2 — Transaction Usage:
        - Ensure explicit `.execute(client)` calls.
        - Verify correct signing order (especially multi-sig).
        - Validate extraction of response properties (`token_id`, `account_id`, `serial_numbers`).
        - Error handling should use `ResponseCode(receipt.status).name`.

        PRIORITY 3 — Naming & Clarity:
        - Role-based naming: `operator_id` / `operator_key`, `treasury_account_id`, etc.
        - Use `_id` for IDs and `_key` for PrivateKey variables.
        - Negative examples must explicitly assert failure codes.
        - Maintain clear, top-to-bottom flow.

        PRIORITY 4 — Imports:
        - Allow top-level OR fully-qualified imports.
        - STRICTLY verify import paths exist in `src/hiero_sdk_python`.
        - Flag hallucinated modules immediately.

        PHILOSOPHY:
        - Examples are user-facing documentation.
        - Prefer explicitness over brevity.
        - Avoid lint-only suggestions.

    # =====================================================
    # UNIT TESTS
    # =====================================================
    - path: "tests/unit/**/*"
      instructions: |
        You are reviewing unit tests for a public SDK.

        CORE RULES:
        - Tests must be deterministic and fail loudly.
        - No network calls.
        - No `print()` statements.
        - No unseeded randomness.

        PRIORITY 1 — Breaking Change Protection:
        - Assert public attributes and return types.
        - Assert fluent setters return `self`.
        - Preserve backward-compatible defaults.
        - Deprecations must be explicitly tested.

        PRIORITY 2 — Constructors & Setters:
        - Test valid, invalid, and edge-case inputs.
        - Ensure validation raises clear exceptions.

        PRIORITY 3 — Coverage:
        - Cover happy and unhappy paths.
        - Avoid brittle ordering unless contractual.

        PRIORITY 4 — Imports:
        - No mocks for non-existent SDK modules.
        - Validate import paths against actual structure.

        PHILOSOPHY:
        - Clarity > DRY.
        - Tests protect future SDK users.

    # =====================================================
    # INTEGRATION TESTS
    # =====================================================
    - path: "tests/integration/**/*"
      instructions: |
        You are reviewing integration tests validating real network behavior.

        SAFETY:
        - No implicit mainnet usage.
        - Credentials must come from environment variables.
        - Failures must be diagnosable.

        PRIORITY 1 — End-to-End Validation:
        - Full lifecycle: construct → freeze → sign → execute → verify.
        - Assert resulting state, not just SUCCESS.
        - Validate IDs, balances, ownership, allowances.

        PRIORITY 2 — Structure:
        - One major behavior per test.
        - Readable names, brief docstrings.
        - Minimal abstraction.

        PRIORITY 3 — Isolation:
        - Avoid state leakage.
        - Recommend teardown or fixture improvements where needed.

        PHILOSOPHY:
        - Reliable, safe, maintainable network tests.

    # =====================================================
    # CORE SDK — GLOBAL RULES
    # =====================================================
    - path: "src/hiero_sdk_python/**/*"
      instructions: |
        This is a public Python SDK.
        Code under `src/hiero_sdk_python` is a long-term compatibility contract.

        CORE PRINCIPLE — SDK CODE IS A CONTRACT:
        - Public APIs are hard to change.
        - Any breaking change MUST be flagged.
        - Prefer explicit, defensive code.
        - Errors must be precise and actionable.

        PRIORITY 1 — Public API Stability:
        - Identify public classes, functions, and attributes.
        - Pay attention to exports via `__init__.py`.
        - Flag renames, signature changes, default changes, or behavior changes.
        - Deprecations require warnings and transitional behavior.

        PRIORITY 2 — Lifecycle Correctness:
        - Transactions: freeze → sign → execute.
        - Queries must NOT follow transaction lifecycles.
        - Serialization (`to_bytes` / `from_bytes`) must be symmetric and lossless.

        PRIORITY 3 — Type Safety:
        - Fail fast on invalid input.
        - Avoid silent coercions.
        - Handle enums defensively.

        PRIORITY 4 — Architecture:
        - Enforce consistent patterns across modules.
        - Avoid duplicated logic.
        - Prevent internal helpers from becoming public APIs.

        PRIORITY 5 — Imports (STRICT):
        - All imports must exist within `src/hiero_sdk_python`.
        - Flag hallucinated modules immediately.
        - Prefer absolute imports.
        - Avoid circular dependencies.

        PRIORITY 6 — Error Handling:
        - Preserve root causes.
        - Avoid swallowing exceptions.
        - Surface gRPC and network errors meaningfully.

        AVOID:
        - Linting or formatting feedback.
        - Large refactors unless correctness is impacted.

        PHILOSOPHY:
        - Review as a downstream user upgrading versions.
        - Favor compatibility over elegance.

    # =====================================================
    # TRANSACTIONS
    # =====================================================
    - path: "src/hiero_sdk_python/transaction/**/*"
      instructions: |
        Transactions are stateful, executable operations.

        REQUIRED LIFECYCLE:
        construct → configure → freeze() → sign() → execute()

        STRICT RULES:
        - Cannot execute before freeze.
        - Signing only allowed after freeze.
        - No mutation after freezing.
        - Node-specific signatures must remain isolated.

        Do NOT suggest reimplementing lifecycle logic in subclasses.

    # =====================================================
    # QUERIES
    # =====================================================
    - path: "src/hiero_sdk_python/query/**/*"
      instructions: |
        Queries are read-only and stateless.

        QUERY LIFECYCLE:
        construct → configure → execute()

        STRICT RULES:
        - Queries MUST NOT be frozen.
        - Queries MUST NOT require signing unless explicitly mandated.
        - Queries MUST NOT mutate client or network state.

    # =====================================================
    # TOKEN TRANSACTIONS
    # =====================================================
    - path: "src/hiero_sdk_python/tokens/**/*"
      instructions: |
        Token operations are specializations of Transaction.

        INHERITANCE RULES:
        - Token classes MUST inherit transaction lifecycle behavior.
        - Do NOT reimplement freeze, sign, execute, retry, or node selection logic.
        - Token classes should only define token-specific fields and validation.

chat:
  art: false
  auto_reply: false

interaction:
  comment_trigger: true
  require_mention: true
