# This workflow warns the team about P0 issues immediately when they are created.
name: P0 Issue Alert
on:
  issues:
    types:
      - labeled

permissions:
  issues: write
  contents: read

jobs:
  p0_notify_team:
    runs-on: hl-sdk-py-lin-md
    # Only run for issues labeled with 'p0' (case-insensitive)
    if: >
      (github.event_name == 'issues' && (
          (github.event.label.name == 'p0' || github.event.label.name == 'P0'))
      )

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Notify team of P0 issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #v9.0.0
        with:
          script: |
            const script = require('./.github/scripts/bot-p0-issues-notify-team.js');
            await script({ github, context});
