# This workflow notifies the GFI support team when an issue is labeled as GFI Candidate.

name: Good First Issue Candidate Notification

on:
  issues:
    types:
      - labeled

permissions:
  issues: write
  contents: read

jobs:
  gfi_candidate_notify_team:
    runs-on: hl-sdk-py-lin-md
    if: contains(github.event.issue.labels.*.name, 'good first issue candidate')
    concurrency:
      group: gfi-candidate-${{ github.event.issue.number }}
      cancel-in-progress: false

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Notify team of GFI candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ github.repository_owner != 'hiero-ledger' }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  #v9.0.0
        with:
          script: |
            const script = require('./.github/scripts/bot-gfi-candidate-notification.js');
            await script({ github, context });
